apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: redhat123
  MARIADB_DATABASE: baran
  MARIADB_USER: ayuub
  MARIADB_PASSWORD: redhat123

